apiVersion: v1
kind: ServiceAccount
metadata:
  name: blue-serviceaccount
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: blue
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: blue
    color: blue

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: blue
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: blue
    color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: blue
  template:
    metadata:
      labels:
        app: nginx
        color: blue
    spec:
      serviceAccountName: blue-serviceaccount
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: blue-nginx-service
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: blue
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: blue
    color: blue
spec:
  ports:
  - port: 80
  selector:
    app: nginx
    color: blue
