apiVersion: v1
kind: ServiceAccount
metadata:
  name: green-serviceaccount
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: green
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: green
    color: green
    nginxGroupScheduleDemo: "yes"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-nginx-deployment
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: green
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: green
    color: green
    nginxGroupScheduleDemo: "yes"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: green
  template:
    metadata:
      labels:
        app: nginx
        color: green
    spec:
      serviceAccountName: green-serviceaccount
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          resources:
            requests:
              # Update cpu and memory with values that will occupy the most of your cluster resources
              cpu: 500m
              memory: 250M

---

apiVersion: v1
kind: Service
metadata:
  name: green-nginx-service
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: green
    app.kubernetes.io/version: "1.7.9"
    app.kubernetes.io/managed-by: kubernetes
    app.kubernetes.io/part-of: green
    color: green
    nginxGroupScheduleDemo: "yes"
spec:
  ports:
    - port: 80
  selector:
    app: nginx
    color: green
