apiVersion: policy.elotl.co/v1alpha1
kind: SchedulePolicy
metadata:
  name: demo-policy
spec:
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: nginx-group-demo
  groupBy:
    labelKey: color
  resourceSelectors:
    labelSelectors:
      - matchLabels:
          nginxGroupScheduleDemo: "yes"
