apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-benchmark
spec:
  args:
    - name: host
  metrics:
    - name: http-benchmark
      failureLimit: 1
      interval: 5s
      count: 1
      provider:
        job:
          metadata:
            labels:
              role: placeholder
              app: rollouts-demo
          spec:
            parallelism: 2
            template:
              spec:
                containers:
                  - name: load-tester
                    image: argoproj/load-tester:latest
                    command: [sh, -xec]
                    args:
                      - |
                        wrk -t1 -c1 -d5 -s report.lua http://{{args.host}}/color
                        jq -e '.errors_ratio <= 0.05' report.json
                restartPolicy: Never
            backoffLimit: 0
