apiVersion: v1
kind: Secret
metadata:
  name: cluster1-pgbackrest-secrets
  labels:
    psql-cluster: all
type: Opaque
data:
  s3.conf: W2dsb2JhbF0KcmVwbzMtczMta2V5PUFLSUEyQkNJUE9OQzRVR05LVFdPCnJlcG8zLXMzLWtleS1zZWNyZXQ9OU8zZy9PcEpaQTg0dWFueU1sQVM2YVZwdEZISzlvOFdMVGxyRDlaWA==
